# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc43d0eed4acb6e5ab1ab1269317d325b0d8fa43962e3c97591a39046d3fc4b4d7fed2518058b30c59714fbfe62c706ed5031391adf121453e9c8780dd6b9a53

test:
  secret_key_base: 9a6f487b7265bd429d5a0acfefa2818f2b62d21a072cc5c11a3a17a1bd1f25f1c43b5c67f192ae7eafc96037eaba43e97a307104549e280de860b0ba24f1e361

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
